language: rust
rust:
- stable

cache: cargo

before_deploy:
  - mkdir ${TRAVIS_BUILD_DIR}/public
  - tar -zcvf ${TRAVIS_BUILD_DIR}/public/linux-packet_generator.tar.gz target/*/packet_generator
  - export TRAVIS_TAG=idl-latest
deploy:
  provider: releases
  name: idl-latest
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: e1FwF79BUgccdEZNRAsyQODmF9singbmoj+OzJo3Q23t9AUh3uuTnDKGwtPHEyQPLBjBMjw9RR4BI8QilFQxgFJoPBKNXK/zthmzxT5qiqEn9rvSh2oTzGDv1RFFNm2JYK2hradWn/IR64yezeVWSt4FSyQhOHjySlyhJRNG/RUeCIMxWJhIURbZzIw80ZHjXhpnfMx0Dg6d/HJ5fJHGvljGByASPJFXej9xDgfdkVEjkHkHvv8oHhinNqU5FI7yHluh7GYnJPcsJjsIKDBeWaVHzRWKBTzVLtWNfP/rIh9hutZT3JRVSZsBb2vgTF2cYsjUr+OaCkSfqFpHyjcfSKRcEgd4D8LEvcI8lfnBsiJb4O7l1mDH3hN/7z2iLX/snJkV3ievtutx9ioHnN6XS4bKJmsT2ROZ+rfLDmExs0ZCvIZ1qcUpJWIF3B350ScZYU9dnabNxO0KEqFl/y+jP5NySCA/jglGzwb/lLrOmP7+m7Vkl0YDMKcDprnax7n5YBWhI9sPnDztNJS2Bz+wbHXMXyzNcQ/Viog62O14ce9dofS3jWNUCfKo+6H7cGSLYxBsuXZ2Zfyi8wA1HO+4EW7jujHQBuGGAB2Lc6hMZAY/5OtbGWrWLwQ+0DPp7qyJGg66qimZyG5t9kIsbg3CpUiqzpspDChVT0pjHUqo9u8=
  file: ${TRAVIS_BUILD_DIR}/public/linux-packet_generator.tar.gz
  on:
    repo: dev-osrose/IDL