language: rust
rust:
- stable
cache: cargo
before_deploy:
- mkdir ${TRAVIS_BUILD_DIR}/public
- tar -zcvf ${TRAVIS_BUILD_DIR}/public/linux-packet_generator.tar.gz target/*/packet_generator
- export TRAVIS_TAG=idl-latest
deploy:
  provider: releases
  name: idl-latest
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: qJeXExz0tx4bV/lXiE975Ec8akv1dBtTc99Oeta0YBTwz6C5MWNlwKh6+/CUnoJwhY14y17mLAMZj/DsdW8tKAHG0FOKKGN3HVb/5KxG2kBdhpsb5nqWI2HNiR5Z5dTYae5Kj4v5iIfa7VJvjiuJwYoV6IJ3rWorc9RBbnrSeGiTMhzIy/+5rvDiA8vDWIJSuvTgMC6YGhkZjQsVEVnnuOstTDqDskKyKVM09LA+sUEKyMuQwFb19D9KnVpwNv+yfrMLFCLVOj/63YcCF60b83SkBHDuMnArwcHcmfZckTqMWTJveXcI3LVeWnqNtiqs1NxWn7W83BR47Y1/cVVa1eZzZhevy7jTRRNPJQtY5rZ2vsWl/t211ABAyUkQBaVuaDB2tSojd5eOphPuoTEU3ZUPpJfJG/dv5VkxE8Whv4Fa3PUg5eo6ncEmJO9RueEo74F3xDWgXTxd8GWIfgiuL674q1+c15ytoM/SqnRkSnXzO5bEB+zDW2rJOy+MzBOdczfKeqUKYqTa2wf8iP/SV2nfdnN2KUgo55DWfcwO8KbxdZBWosDJAa1zylU6SC8znrnAblQ0xDpBx9ft+Yson1V/PQ9ErbLoulJVAcNmBX25cWPzhjx6rOnObwCBgr6dBIIy0wBDlscdo6AZnY4zirg0JY6kkskp+6kuWFNpD6o=
  file: "${TRAVIS_BUILD_DIR}/public/linux-packet_generator.tar.gz"
  on:
    repo: dev-osrose/IDL
